services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}" # Map Vite's default dev server port
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      NODE_ENV: development
      PORT: ${PORT}