# Use the official Node.js image
FROM node:22.14.0-alpine

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the development server port
EXPOSE ${PORT}

# Start the development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
#CMD ["npm", "run", "dev"]